[2025-07-21 11:52:50 +0800] [158464] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5020']
  backlog: 2048
  workers: 4
  worker_class: sync
  threads: 4
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 300
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: True
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/st426/change-clothes
  daemon: False
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: None
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: gunicorn_error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: server:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7b34c089c720>
  on_reload: <function OnReload.on_reload at 0x7b34c089c860>
  when_ready: <function WhenReady.when_ready at 0x7b34c089c9a0>
  pre_fork: <function Prefork.pre_fork at 0x7b34c089cb80>
  post_fork: <function Postfork.post_fork at 0x7b34c089ccc0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7b34c089ce00>
  worker_int: <function WorkerInt.worker_int at 0x7b34c089cf40>
  worker_abort: <function WorkerAbort.worker_abort at 0x7b34c089d080>
  pre_exec: <function PreExec.pre_exec at 0x7b34c089d1c0>
  pre_request: <function PreRequest.pre_request at 0x7b34c089d300>
  post_request: <function PostRequest.post_request at 0x7b34c089d3a0>
  child_exit: <function ChildExit.child_exit at 0x7b34c089d4e0>
  worker_exit: <function WorkerExit.worker_exit at 0x7b34c089d620>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7b34c089d760>
  on_exit: <function OnExit.on_exit at 0x7b34c089d8a0>
  ssl_context: <function NewSSLContext.ssl_context at 0x7b34c089da80>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2025-07-21 11:52:50 +0800] [158464] [INFO] Starting gunicorn 23.0.0
[2025-07-21 11:52:50 +0800] [158464] [ERROR] Connection in use: ('0.0.0.0', 5020)
[2025-07-21 11:52:50 +0800] [158464] [ERROR] connection to ('0.0.0.0', 5020) failed: [Errno 98] Address already in use
[2025-07-21 11:52:50 +0800] [158464] [DEBUG] Retrying in 1 second.
[2025-07-21 11:52:51 +0800] [158464] [ERROR] Connection in use: ('0.0.0.0', 5020)
[2025-07-21 11:52:51 +0800] [158464] [ERROR] connection to ('0.0.0.0', 5020) failed: [Errno 98] Address already in use
[2025-07-21 11:52:51 +0800] [158464] [DEBUG] Retrying in 1 second.
[2025-07-21 11:52:52 +0800] [158464] [ERROR] Connection in use: ('0.0.0.0', 5020)
[2025-07-21 11:52:52 +0800] [158464] [ERROR] connection to ('0.0.0.0', 5020) failed: [Errno 98] Address already in use
[2025-07-21 11:52:52 +0800] [158464] [DEBUG] Retrying in 1 second.
[2025-07-21 11:52:53 +0800] [158464] [ERROR] Connection in use: ('0.0.0.0', 5020)
[2025-07-21 11:52:53 +0800] [158464] [ERROR] connection to ('0.0.0.0', 5020) failed: [Errno 98] Address already in use
[2025-07-21 11:52:53 +0800] [158464] [DEBUG] Retrying in 1 second.
[2025-07-21 11:52:54 +0800] [158464] [ERROR] Connection in use: ('0.0.0.0', 5020)
[2025-07-21 11:52:54 +0800] [158464] [ERROR] connection to ('0.0.0.0', 5020) failed: [Errno 98] Address already in use
[2025-07-21 11:52:54 +0800] [158464] [DEBUG] Retrying in 1 second.
[2025-07-21 11:52:55 +0800] [158464] [ERROR] Can't connect to ('0.0.0.0', 5020)
